server.port=8081
spring.application.name=expensetracker

spring.datasource.url=jdbc:postgresql://localhost:5432/expensetracker
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# JWT Configuration
jwt.secret=mySecretKeyForJwtTokenGenerationMustBe256BitsLongForHS256AlgorithmSecureKey123
jwt.expiration=86400000


# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123


# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.devvikram.expensetracker=DEBUG

# Error Handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false





